package functional

import (
	"time"
)

var testEpics epicList = epicList{
	{
		InternalName:      "TestIntName1",
		InternalDesc:      "TestIntDesc1",
		Author:            "TestAuthor1",
		AuthorSite:        "TestAuthorSite1",
		AuthorEmail:       "TestAuthorEmail1",
		AuthorPublic:      false,
		AuthorSitePublic:  false,
		AuthorEmailPublic: false,
		StartDate:         NegativeInfinityTS,
		EndDate:           PositiveInfinityTS,
		GroupSize:         1,
		Visibility:        "ALWAYS",
		Name:              "TestName1",
		StartText:         "TestStart1",
		SuccessText:       "TestSuccess1",
		FailText:          "TestFail1",
		Desc:              "TestDesc1",
		InProgressDesc:    "TestInProgDesc1",
		CompleteDesc:      "TestCompleteDesc1",
		LongDesc:          "TestLongDesc1",
		RepeatCount:       1,
		Language:          "en",
		Flags:             0,
		QuestMap: []epicQuestMapEntry{
			{
				LogicGroup: 0,
				DisplayID:  0,
				QuestName:  "TestQuest1",
				Modality:   "MANDATORY",
			},
		},
	},
	{
		InternalName:      "TestIntName2",
		InternalDesc:      "TestIntDesc2",
		Author:            "TestAuthor2",
		AuthorSite:        "TestAuthorSite2",
		AuthorEmail:       "TestAuthorEmail2",
		AuthorPublic:      false,
		AuthorSitePublic:  false,
		AuthorEmailPublic: false,
		StartDate:         NegativeInfinityTS,
		EndDate:           PositiveInfinityTS,
		GroupSize:         1,
		Visibility:        "ALWAYS",
		Name:              "TestName2",
		StartText:         "TestStart2",
		SuccessText:       "TestSuccess2",
		FailText:          "TestFail2",
		Desc:              "TestDesc2",
		InProgressDesc:    "TestInProgDesc2",
		CompleteDesc:      "TestCompleteDesc2",
		LongDesc:          "TestLongDesc2",
		RepeatCount:       5,
		Language:          "en",
		Flags:             0,
		QuestMap: []epicQuestMapEntry{
			{
				LogicGroup: 0,
				DisplayID:  0,
				QuestName:  "TestQuest1",
				Modality:   "MANDATORY",
			},
			{
				LogicGroup: 1,
				DisplayID:  0,
				QuestName:  "TestQuest3",
				Modality:   "OPTIONAL",
			},
			{
				LogicGroup: 1,
				DisplayID:  1,
				QuestName:  "TestQuest4",
				Modality:   "MANDATORY",
			},
		},
	},
	{
		InternalName:      "TestIntName3",
		InternalDesc:      "TestIntDesc3",
		Author:            "TestAuthor3",
		AuthorSite:        "TestAuthorSite3",
		AuthorEmail:       "TestAuthorEmail3",
		AuthorPublic:      false,
		AuthorSitePublic:  false,
		AuthorEmailPublic: false,
		StartDate:         time.Now().Add(1 * time.Hour),
		EndDate:           PositiveInfinityTS,
		GroupSize:         1,
		Visibility:        "ALWAYS",
		Name:              "TestName3",
		StartText:         "TestStart3",
		SuccessText:       "TestSuccess3",
		FailText:          "TestFail3",
		Desc:              "TestDesc3",
		InProgressDesc:    "TestInProgDesc3",
		CompleteDesc:      "TestCompleteDesc3",
		LongDesc:          "TestLongDesc3",
		RepeatCount:       1,
		Language:          "en",
		Flags:             0,
	},
	{
		InternalName:      "TestIntName4",
		InternalDesc:      "TestIntDesc4",
		Author:            "TestAuthor4",
		AuthorSite:        "TestAuthorSite4",
		AuthorEmail:       "TestAuthorEmail4",
		AuthorPublic:      false,
		AuthorSitePublic:  false,
		AuthorEmailPublic: false,
		StartDate:         time.Now().Add(1 * time.Hour),
		EndDate:           time.Now().Add(2 * time.Hour),
		GroupSize:         1,
		Visibility:        "ALWAYS",
		Name:              "TestName4",
		StartText:         "TestStart4",
		SuccessText:       "TestSuccess4",
		FailText:          "TestFail4",
		Desc:              "TestDesc4",
		InProgressDesc:    "TestInProgDesc4",
		CompleteDesc:      "TestCompleteDesc4",
		LongDesc:          "TestLongDesc4",
		RepeatCount:       1,
		Language:          "en",
		Flags:             0,
	},
	{
		InternalName:      "TestIntName5",
		InternalDesc:      "TestIntDesc5",
		Author:            "TestAuthor5",
		AuthorSite:        "TestAuthorSite5",
		AuthorEmail:       "TestAuthorEmail5",
		AuthorPublic:      false,
		AuthorSitePublic:  false,
		AuthorEmailPublic: false,
		StartDate:         NegativeInfinityTS,
		EndDate:           PositiveInfinityTS,
		GroupSize:         1,
		Visibility:        "HIDDEN",
		Name:              "TestName5",
		StartText:         "TestStart5",
		SuccessText:       "TestSuccess5",
		FailText:          "TestFail5",
		Desc:              "TestDesc5",
		InProgressDesc:    "TestInProgDesc5",
		CompleteDesc:      "TestCompleteDesc5",
		LongDesc:          "TestLongDesc5",
		RepeatCount:       1,
		Language:          "en",
		Flags:             0,
		ActivationRegex:   strPtr("^testActivate$"),
	},
	{
		InternalName:      "TestIntName6",
		InternalDesc:      "TestIntDesc6",
		Author:            "TestAuthor6",
		AuthorSite:        "TestAuthorSite6",
		AuthorEmail:       "TestAuthorEmail6",
		AuthorPublic:      false,
		AuthorSitePublic:  false,
		AuthorEmailPublic: false,
		StartDate:         NegativeInfinityTS,
		EndDate:           PositiveInfinityTS,
		GroupSize:         1,
		Visibility:        "ELIGIBLE",
		Name:              "TestName6",
		StartText:         "TestStart6",
		SuccessText:       "TestSuccess6",
		FailText:          "TestFail6",
		Desc:              "TestDesc6",
		InProgressDesc:    "TestInProgDesc6",
		CompleteDesc:      "TestCompleteDesc6",
		LongDesc:          "TestLongDesc6",
		RepeatCount:       1,
		Language:          "en",
		Flags:             0,
	},
	{
		InternalName:      "TestIntName7",
		InternalDesc:      "TestIntDesc7",
		Author:            "TestAuthor7",
		AuthorSite:        "TestAuthorSite7",
		AuthorEmail:       "TestAuthorEmail7",
		AuthorPublic:      false,
		AuthorSitePublic:  false,
		AuthorEmailPublic: false,
		StartDate:         NegativeInfinityTS,
		EndDate:           PositiveInfinityTS,
		GroupSize:         1,
		Visibility:        "ELIGIBLE",
		Name:              "TestName7",
		StartText:         "TestStart7",
		SuccessText:       "TestSuccess7",
		FailText:          "TestFail7",
		Desc:              "TestDesc7",
		InProgressDesc:    "TestInProgDesc7",
		CompleteDesc:      "TestCompleteDesc7",
		LongDesc:          "TestLongDesc7",
		RepeatCount:       1,
		Language:          "en",
		Flags:             0,
	},
	{
		InternalName:      "TestIntName8",
		InternalDesc:      "TestIntDesc8",
		Author:            "TestAuthor8",
		AuthorSite:        "TestAuthorSite8",
		AuthorEmail:       "TestAuthorEmail8",
		AuthorPublic:      false,
		AuthorSitePublic:  false,
		AuthorEmailPublic: false,
		StartDate:         NegativeInfinityTS,
		EndDate:           PositiveInfinityTS,
		GroupSize:         1,
		Visibility:        "ELIGIBLE",
		Name:              "TestName8",
		StartText:         "TestStart8",
		SuccessText:       "TestSuccess8",
		FailText:          "TestFail8",
		Desc:              "TestDesc8",
		InProgressDesc:    "TestInProgDesc8",
		CompleteDesc:      "TestCompleteDesc8",
		LongDesc:          "TestLongDesc8",
		RepeatCount:       1,
		Language:          "en",
		Flags:             0,
	},
	{
		InternalName:      "TestIntName9",
		InternalDesc:      "TestIntDesc9",
		Author:            "TestAuthor9",
		AuthorSite:        "TestAuthorSite9",
		AuthorEmail:       "TestAuthorEmail9",
		AuthorPublic:      false,
		AuthorSitePublic:  false,
		AuthorEmailPublic: false,
		StartDate:         NegativeInfinityTS,
		EndDate:           PositiveInfinityTS,
		GroupSize:         1,
		Visibility:        "HIDDEN",
		Name:              "TestName9",
		StartText:         "TestStart9",
		SuccessText:       "TestSuccess9",
		FailText:          "TestFail9",
		Desc:              "TestDesc9",
		InProgressDesc:    "TestInProgDesc9",
		CompleteDesc:      "TestCompleteDesc9",
		LongDesc:          "TestLongDesc9",
		RepeatCount:       1,
		Language:          "en",
		Flags:             0,
		ActivationRegex:   strPtr("^testActivate$"),
	},
	{
		InternalName:      "TestIntName10",
		InternalDesc:      "TestIntDesc10",
		Author:            "TestAuthor10",
		AuthorSite:        "TestAuthorSite10",
		AuthorEmail:       "TestAuthorEmail10",
		AuthorPublic:      false,
		AuthorSitePublic:  false,
		AuthorEmailPublic: false,
		StartDate:         NegativeInfinityTS,
		EndDate:           PositiveInfinityTS,
		GroupSize:         1,
		Visibility:        "HIDDEN",
		Name:              "TestName10",
		StartText:         "TestStart10",
		SuccessText:       "TestSuccess10",
		FailText:          "TestFail10",
		Desc:              "TestDesc10",
		InProgressDesc:    "TestInProgDesc10",
		CompleteDesc:      "TestCompleteDesc10",
		LongDesc:          "TestLongDesc10",
		RepeatCount:       1,
		Language:          "en",
		Flags:             0,
		ActivationRegex:   strPtr("^lkajsdauelkjasd$"),
	},
	{
		InternalName:      "TestIntName11_Remote",
		InternalDesc:      "TestIntDesc11_Remote",
		Author:            "TestAuthor11_Remote",
		AuthorSite:        "TestAuthorSite11_Remote",
		AuthorEmail:       "TestAuthorEmail11_Remote",
		AuthorPublic:      false,
		AuthorSitePublic:  false,
		AuthorEmailPublic: false,
		StartDate:         NegativeInfinityTS,
		EndDate:           PositiveInfinityTS,
		GroupSize:         1,
		Visibility:        "HIDDEN",
		Name:              "TestName11_Remote",
		StartText:         "TestStart11_Remote",
		SuccessText:       "TestSuccess11_Remote",
		FailText:          "TestFail11_Remote",
		Desc:              "TestDesc11_Remote",
		InProgressDesc:    "TestInProgDesc11_Remote",
		CompleteDesc:      "TestCompleteDesc11_Remote",
		LongDesc:          "TestLongDesc11_Remote",
		RepeatCount:       1,
		Language:          "en",
		Flags:             0,
		ActivationRegex:   strPtr("^11remote$"),
		QuestMap: []epicQuestMapEntry{
			{
				LogicGroup: 0,
				DisplayID:  0,
				QuestName:  "TestQuest2_Remote",
				Modality:   "MANDATORY",
			},
		},
	},
}

var testRequiredEpics []reqEpic = []reqEpic{
	{
		InternalName:      "TestIntName6",
		RequiredEpicNames: []string{"TestIntName1", "TestIntName2"},
	},
	{
		InternalName:      "TestIntName7",
		RequiredEpicNames: []string{"TestIntName3"},
	},
	{
		InternalName:      "TestIntName8",
		RequiredEpicNames: []string{"TestIntName6", "TestIntName7"},
	},
}
